#!/usr/bin/bash

# to use your own data, this automatically sets USER to be your username
#USER=${USER:-`whoami`}
USER_LIST_FILE=$1
DATA=/Volumes/Network/courses/sp/data
# and this is the path to where your data was placed by the make_mfccs script
#DATA=${DATA:-/Volumes/Network/courses/sp/data_upload}
#DATA=${DATA:-/Volumes/Network/courses/sp/data}



# later, to use another user's data, for example "simonk"
# USER=simonk
# and to access all data from all years, use this path
# DATA=${DATA:-/Volumes/Network/courses/sp/data}

shopt -s extglob

for USER in `cat ${USER_LIST_FILE}`
do
    #echo $USER
    for F in `ls ${DATA}/mfcc/test/${USER}_test?(_)??.mfcc`
    do
	FF=`basename $F .mfcc`
	
	#echo
	#echo Doing $F
	
	HVite -T 0 -C resources/CONFIG \
	    -d models/hmm1 \
	    -l rec \
	    -w resources/grammar_as_network \
	    resources/dictionary \
	    resources/word_list \
	    $F

    done
done
