#!/usr/bin/bash

USER=$1
DATA=${DATA:-/Volumes/Network/courses/sp/data}

shopt -s extglob

for F in `ls ${DATA}/mfcc/test/${USER}_test?(_)??.mfcc`
do
 FF=`basename $F .mfcc`

 #echo
 #echo Doing $F

 HVite -T 0 -C resources/CONFIG \
	-d models/hmm1 \
	-l rec \
	-w resources/grammar_as_network \
	resources/dictionary \
	resources/word_list \
	$F

done
