#!/usr/bin/bash

USER_LIST=$1

rm sanity_users.txt

for USER in `cat ${USER_LIST}`
do
    echo $USER
    # Initialising models
    ./scripts/initialise_models_single ${USER}
    
    # Training models
    ./scripts/train_models_single ${USER}
    
    if [ -z "$(ls -A rec)" ]; then
	echo "Empty"
    else
	rm rec/*
    fi

    # Testing and evaluating
    ./scripts/recognise_test_data_single ${USER}

    WOR=$(./scripts/results ${USER} | grep WORD | \
	cut -d "=" -f3 | cut -d" " -f1 | awk '{print 100 - $1}')
    
    WOR_INT=${WOR/.*}
    echo ${WOR_INT}
    if ((${WOR_INT} < 20))
    then
	echo $USER passes the test
	echo $USER >> sanity_users.txt	
    fi

    rm models/hmm0/*
    rm models/hmm1/*

done

