#!/usr/bin/bash

USER_LIST=$1

rm bad_users.txt

for USER in `cat ${USER_LIST}`
do
    echo $USER
    STATUS=pass
    # Initialising models
    ./scripts/initialise_models_single ${USER} || STATUS=fail
    echo initialised
    
    # Training models
    ./scripts/train_models_single ${USER} || STATUS=fail
    echo trained
    
    if [ -z "$(ls -A rec)" ]; then
	rm rec/*
    fi

    # Testing and evaluating
    ./scripts/recognise_test_data_single ${USER} || STATUS=fail
    echo tested
    WOR=$(./scripts/results ${USER} | grep WORD | \
	cut -d "=" -f3 | cut -d" " -f1 | awk '{print 100 - $1}')
    
    echo $WOR
    if [ $WOR -gt 10 ] | [ $STATUS = "fail" ]
    then
	echo $STATUS
	echo User $USER has a WOR of $WOR, does not pass the test
	echo $USER >> bad_users.txt	
    fi

done

