#!/usr/bin/bash

# to use your own data, this automatically sets USER to be your username
#USER=${USER:-`whoami`}
MFCC_LIST_FILE=$1
DATA=/Volumes/Network/courses/sp/data
# and this is the path to where your data was placed by the make_mfccs script
#DATA=${DATA:-/Volumes/Network/courses/sp/data_upload}
#DATA=${DATA:-/Volumes/Network/courses/sp/data}
# later, to use another user's data, for example "simonk"
# USER=simonk
# and to access all data from all years, use this path
# DATA=${DATA:-/Volumes/Network/courses/sp/data}

# train each initialised model
#for USER in `cat ${USER_LIST}`
#do
    for WORD in `cat resources/word_list`
    do
	
	#echo training model of $WORD
	
	HRest -T 0 \
	    -G ESPS \
            -m 1 \
	    -S ${MFCC_LIST_FILE} \
            -C resources/CONFIG \
            -l $WORD \
            -M models/hmm1 \
            -L ${DATA}/lab/train/ \
	    models/hmm0/$WORD
	    #${DATA}/mfcc/train/${USER}_train.mfcc

    done
#done

